name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: testSine01
      id: testsine01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testSine01
        setup-command: ''
        command: assertTrue(Math.abs(TaylorSeries.sin(Math.PI/6) - 0.5) < 1E-6);
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTSINE01_RESULTS: "${{steps.testsine01.outputs.result}}"
      with:
        runners: testsine01
